services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/client
    working_dir: /usr/src/client
    depends_on:
      - database
      - server

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./server:/usr/src/server
    working_dir: /usr/src/server
    depends_on:
      - database

  database:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: database
      MARIADB_ROOT_PASSWORD: secret
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mariadb_data:
